import { spawnSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const repoRoot = path.resolve(import.meta.dirname, '..')
const generatedHeaderText = 'generated by scripts/generate.ts from src/schema'

describe('generate --check', () => {
  it('exits 0 and reports the checked-in generated files as current', () => {
    const proc = spawnSync('node', ['--import', 'tsx', 'scripts/generate.ts', '--check'], {
      cwd: repoRoot,
      encoding: 'utf8',
    })

    expect(proc.status).toBe(0)
    expect(proc.stdout).toContain('generated files are current')
  })

  for (const file of ['README.md', 'skills/ecfr/SKILL.md', 'docs/capabilities.json']) {
    it(`${file} carries the generated header`, () => {
      const content = readFileSync(path.join(repoRoot, file), 'utf8')
      expect(content).toContain(generatedHeaderText)
    })
  }
})
