import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { pathToFileURL } from 'node:url'
import { z } from 'zod'
import {
  envelopeSchema,
  errorSchema,
  exitCodeTable,
  flags,
  formatLintIssues,
  globalFlagKeys,
  lintOperations,
  operations,
  policy,
  type AnyOperation,
  type FlagKey,
} from '../src/schema/index.js'

const root = path.resolve(import.meta.dirname, '..')
const generatedComment = 'generated by scripts/generate.ts from src/schema — do not edit by hand'
const readmeStart = '<!-- generated:commands:start -->'
const readmeEnd = '<!-- generated:commands:end -->'
const generatedHeader = `<!-- ${generatedComment} -->`

const skillFrontmatter = `---
name: ecfr
description: Look up, search, browse, and read federal regulations from the Code of Federal Regulations (CFR) using the ecfr CLI. Use when the user asks about federal regulations, CFR text, regulatory requirements, compliance rules, DFARS, NIST references in the CFR, CUI rules, acquisition regulations (FAR/DFARS), or needs to check what a specific CFR section says. Also use when tasks require reading regulatory text to answer compliance questions, verify regulatory citations, track regulation changes, or find which agencies own which CFR titles.
---`

const skillHandwritten = `## Key CFR Titles for CMMC/Defense Work

| Title | Name | Common Use |
|-------|------|------------|
| 32 | National Defense | NIST 800-171 references, CUI rules (Part 2002) |
| 48 | Federal Acquisition Regulations (FAR) | FAR/DFARS clauses (Part 252 = DFARS) |
| 15 | Commerce and Foreign Trade | Export controls, EAR |
| 22 | Foreign Relations | ITAR (Parts 120-130) |

## Common Workflows

**Find what a CFR section says:**
1. \`ecfr structure <title>\` to discover parts/sections
2. \`ecfr read <title> --part <n> --section <n>\` to read the text

**Search for a regulatory topic:**
1. \`ecfr counts "<query>"\` to see where matches cluster
2. \`ecfr search "<query>" --title <n>\` to get excerpts from a specific title

**Check if a regulation changed recently:**
1. \`ecfr changes <title> --part <n> --since <date>\` to see amendments

## Gotchas

- Date format is always \`YYYY-MM-DD\`
- Agency slugs (for \`--agency\`) come from \`ecfr agencies\` — use the slug field, not the name
- The \`read\` command fetches XML from the eCFR API and parses it — large parts (like all of FAR Title 48) can be slow and produce massive output. Always scope with \`--part\` and ideally \`--section\`
- The \`search\` and \`structure\` commands hit the eCFR API which may return errors during maintenance windows — retry once if a 400/404 occurs
- Section numbers in \`--section\` use the full dotted notation (e.g., \`2002.14\`, not just \`14\`)
- Parse \`.data\` for the operation-specific data.
- Check \`.ok\` and the exit code before using the data.
- Quote \`.currency.date\` when citing regulation text.
- Use \`--dry-run\` before large reads.
- \`ecfr capabilities\` prints the full machine readable contract.`

interface GeneratedFile {
  path: string
  content: string
}

interface JsonObject {
  [key: string]: unknown
}

function escapeTable(text: string): string {
  return text.replaceAll('|', '\\|').replaceAll('\n', ' ')
}

function flagRow(key: FlagKey): string {
  const definition = flags[key]
  const value = 'value' in definition && definition.value ? definition.value : 'boolean'
  return `| \`--${definition.name}\` | \`${escapeTable(value)}\` | ${escapeTable(definition.description)} |`
}

function paramsTable(op: AnyOperation): string {
  const rows: string[] = []
  if (op.positional) {
    rows.push(`| \`${op.positional.name}\` (positional) | \`<${op.positional.name}>\` | ${escapeTable(op.positional.description)} |`)
  }
  rows.push(...op.flags.map(flagRow))
  if (rows.length === 0) rows.push('| None | — | This operation has no operation-specific params. |')
  return ['| Flag | Value | Description |', '| --- | --- | --- |', ...rows].join('\n')
}

function examples(op: AnyOperation): string {
  return ['```bash', ...op.examples.map(example => `${example.command} # ${example.description}`), '```'].join('\n')
}

function commandSection(op: AnyOperation): string {
  return `### ${op.summary}

${op.description}

${examples(op)}

${paramsTable(op)}`
}

function globalFlagsTable(): string {
  return [
    '| Flag | Value | Description |',
    '| --- | --- | --- |',
    ...globalFlagKeys.map(flagRow),
  ].join('\n')
}

const envelopeLines = `The JSON envelope uses these top-level keys:

- \`ok\`: whether the operation succeeded.
- \`version\`: the CLI version that produced the envelope.
- \`operation\`: the operation that ran.
- \`request_id\`: the per-invocation identifier echoed to upstream calls.
- \`agent\`: the self-reported agent name for tracing, or null.
- \`target\`: the target that served a successful response.
- \`untrusted\`: dot paths naming fields that hold fetched external content.
- \`params\`: the effective params after defaults.
- \`defaulted\`: the params the CLI filled in.
- \`warnings\`: conditions the caller should react to.
- \`source\`: the upstream URL and fetch time, or null for an offline operation.
- \`currency\`: the issue date and currency dates for a title-scoped operation.
- \`pagination\`: paging details for search, including a ready-to-run \`next\` command.
- \`dry_run\`: whether the operation stopped before fetching data.
- \`data\`: the operation-specific data on success.
- \`error\`: the error code, message, optional field, retryability, remediation, and details on failure.`

function exitCodesTable(): string {
  return [
    '| Exit | Error codes | When |',
    '| ---: | --- | --- |',
    ...exitCodeTable.map(row => `| ${row.exit} | ${row.codes.map(code => `\`${code}\``).join(', ')} | ${escapeTable(row.when)} |`),
  ].join('\n')
}

function readmeBlock(): string {
  return `${generatedHeader}

## Commands

${operations.map(commandSection).join('\n\n')}

## Global flags

${globalFlagsTable()}

## Output modes

| Context | Output |
| --- | --- |
| Default, \`--output json\`, or \`--json\` | The JSON envelope |
| \`--output text\` | Human text |
| \`read --xml\` | Raw XML |
| \`capabilities\` | Always JSON |

## Envelope

${envelopeLines}

## Exit codes

${exitCodesTable()}`
}

const dataDescriptions: Record<string, string[]> = {
  titles: ['`data.titles` holds the CFR title records.'],
  agencies: ['`data.agencies` holds the agency records; `data.total` and `data.matched` hold the unfiltered and returned counts.'],
  structure: ['`data.identifier`, `data.label`, and `data.children` hold the hierarchy tree for the title.'],
  search: ['`data.results` holds matching sections and excerpts; `data.meta` holds upstream paging totals.'],
  counts: ['`data.count` holds the overall count; `data.children` holds counts grouped through the CFR hierarchy.'],
  changes: ['`data.content_versions` holds the title amendment history.'],
  corrections: ['`data.ecfr_corrections` holds correction and errata records.'],
  read: ['`data.title`, `data.date`, `data.content`, and `data.sections` hold the served title, issue date, Content, and per-section metadata.'],
  capabilities: ['This operation is raw output. Its top-level keys describe the CLI, policy, operations, exit codes, flags, and schemas.'],
}

function agentCommandSection(op: AnyOperation): string {
  const notes = [...(dataDescriptions[op.name] ?? ['`data` holds the operation-specific data.'])]
  if (op.titleScoped) notes.push('Read `currency` for the issue date and the eCFR currency dates.')
  if (op.pagination) notes.push('Read `pagination.next` for a ready-to-run command for the next search page, or null at the end.')
  if (op.network === 'remote') notes.push('Use `--dry-run` to inspect `source.url` and the effective params without fetching the data.')
  return `${commandSection(op)}

${notes.join(' ')}`
}

function skillBlock(): string {
  return `${generatedHeader}

## Commands

${operations.map(agentCommandSection).join('\n\n')}

## Output

${envelopeLines}

The fixed network policy makes ${policy.retries} retries after the first attempt, waits ${policy.headers_timeout_ms / 1000} seconds for headers, and allows ${policy.body_timeout_ms / 60000} minutes for the body.

${exitCodesTable()}`
}

function replaceMarkedBlock(source: string, block: string): string | null {
  const start = source.indexOf(readmeStart)
  const end = source.indexOf(readmeEnd)
  if (start === -1 || end === -1 || end < start) return null
  return `${source.slice(0, start + readmeStart.length)}\n${block}\n${source.slice(end)}`
}

function renderReadme(source: string): string {
  const marked = replaceMarkedBlock(source, readmeBlock())
  if (marked !== null) return marked

  const commands = source.indexOf('## Commands')
  const outputModes = source.indexOf('## Output modes', commands)
  if (commands === -1 || outputModes === -1) {
    throw new Error('README.md needs generated markers or existing Commands and Output modes sections')
  }
  const followingHeading = source.indexOf('\n## ', outputModes + '\n## Output modes'.length)
  const end = followingHeading === -1 ? source.length : followingHeading + 1
  const markedBlock = `${readmeStart}\n${readmeBlock()}\n${readmeEnd}\n\n`
  return `${source.slice(0, commands)}${markedBlock}${source.slice(end)}`
}

function initialSkill(): string {
  return `${skillFrontmatter}

${readmeStart}
${skillBlock()}
${readmeEnd}

${skillHandwritten}
`
}

function renderSkill(source: string | null): string {
  if (source === null) return initialSkill()
  const marked = replaceMarkedBlock(source, skillBlock())
  if (marked === null) throw new Error('skills/ecfr/SKILL.md is missing generated markers')
  return marked
}

function commentedJson(value: JsonObject): string {
  return `${JSON.stringify({ $comment: generatedComment, ...value }, null, 2)}\n`
}

async function readOptional(file: string): Promise<string | null> {
  try {
    return await readFile(file, 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null
    throw error
  }
}

async function capabilitiesDocument(): Promise<JsonObject> {
  const operation = operations.find(candidate => candidate.name === 'capabilities')
  if (!operation?.compute) throw new Error('capabilities operation is missing compute()')
  const data = await operation.compute({}, {
    currency: async () => { throw new Error('capabilities must not resolve currency') },
  })
  if (typeof data !== 'object' || data === null || Array.isArray(data)) {
    throw new Error('capabilities operation did not return an object')
  }
  return data as JsonObject
}

export async function renderGeneratedFiles(): Promise<GeneratedFile[]> {
  const issues = lintOperations(operations)
  if (issues.length > 0) throw new Error(formatLintIssues(issues))

  const readmePath = path.join(root, 'README.md')
  const skillPath = path.join(root, 'skills/ecfr/SKILL.md')
  const capabilities = await capabilitiesDocument()
  const files: GeneratedFile[] = [
    { path: readmePath, content: renderReadme(await readFile(readmePath, 'utf8')) },
    { path: skillPath, content: renderSkill(await readOptional(skillPath)) },
    { path: path.join(root, 'docs/capabilities.json'), content: commentedJson(capabilities) },
    { path: path.join(root, 'docs/schemas/envelope.json'), content: commentedJson(z.toJSONSchema(envelopeSchema) as JsonObject) },
    { path: path.join(root, 'docs/schemas/error.json'), content: commentedJson(z.toJSONSchema(errorSchema) as JsonObject) },
  ]

  for (const op of operations) {
    files.push({
      path: path.join(root, `docs/schemas/${op.name}.output.json`),
      content: commentedJson(z.toJSONSchema(op.output) as JsonObject),
    })
  }
  return files
}

export async function generate(check = false): Promise<number> {
  let files: GeneratedFile[]
  try {
    files = await renderGeneratedFiles()
  } catch (error) {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`)
    return 1
  }

  if (check) {
    const differing: string[] = []
    for (const file of files) {
      if (await readOptional(file.path) !== file.content) differing.push(path.relative(root, file.path))
    }
    if (differing.length > 0) {
      process.stdout.write(`${differing.join('\n')}\n`)
      return 1
    }
    process.stdout.write('generated files are current\n')
    return 0
  }

  for (const file of files) {
    await mkdir(path.dirname(file.path), { recursive: true })
    await writeFile(file.path, file.content)
    process.stdout.write(`${path.relative(root, file.path)}\n`)
  }
  return 0
}

const invokedPath = process.argv[1] ? pathToFileURL(path.resolve(process.argv[1])).href : ''
if (import.meta.url === invokedPath) {
  process.exitCode = await generate(process.argv.includes('--check'))
}
